#! /bin/sh
#ObliviousGmn, May 2020

# . "$HOME/.cache/wal/colors.sh"

# Start Ups ..
$HOME/.config/polybar/launch.sh
sxhkd &
picom -c -t-5 -l-5 -r3 -o.50 &
# (wal -q -R &)
(feh --bg-fill /home/richard/Pictures/wallpapers/2.png &)
wmname LG3D

# Workstations ..
bspc monitor ^1 -d 1 2 3
bspc monitor ^2 -d 4 5 6 7
bspc monitor ^3 -d 8 9 0

# Configs ..
bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.53
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding			 25
bspc config focus_follows_pointer false

# Colors ..
bspc config normal_border_color $background
bspc config focused_border_color \#e84f4f

# Windows Rules .. 

# Terminal Station ..
bspc rule -a alacritty desktop='^1' follow=on

# GTK Station ..
# bspc rule -a Gcolor2 desktop='^2' follow=on
bspc rule -a Xfd desktop='^2' follow=on

# Web Station ..
bspc rule -a google-chrome-stable desktop='^3' follow=on
bspc rule -a firefox desktop='^3' follow=on

# Image Station .. 
bspc rule -a feh desktop='^4' state=tiled follow=on
